TSOK/urls.py
from django.contrib import admin
from django.urls import path, include
#from django.conf import settings
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
    path('', include('Top.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Top/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'
urlpatterns = [
  path('', views.index, name='index'),
  path('article/', views.poisck, name='poisck'),
  path('rubric/<int:rubric_id>/', views.by_rubric, name='by_rubric'),
  path('article/<int:article_id>/', views.detail, name='detail'),
  path('article/<int:article_id>/list_comment/', views.list_comment, name='list_comment'),
  path('register/', views.RegisterFormView.as_view(), name='register')
]

Top/models.py
import datetime
from django.db import models
from django.conf import settings
from django.utils import timezone

class Article(models.Model):
  image = models.ImageField('Картинка', upload_to='images/', null=True, blank=True)
  rubric = models.ForeignKey('Rubric', null=True, on_delete=models.PROTECT, verbose_name='Рубрика')
  create_author = models.CharField('Автор идеи', max_length=100)
  title = models.CharField('Название статьи', max_length=200)
  text = models.TextField('Текст статьие', blank=True, null=True)
  created_date = models.DateTimeField(db_index=True, auto_now_add=True)
  published_date = models.DateTimeField(blank=True, null=True, db_index=True, auto_now_add=True)

  class Meta:
    verbose_name = 'Статья'
    verbose_name_plural = 'Статьи'
    ordering = ['-published_date']
    
  def new_article(self):
    return self.published_date >= (timezone.now() - datetime.timedelta(days = 7))

  def publish(self):
    self.published_date = timezone.now()
    self.save()

  def __str__(self):
    return self.title

class Comment(models.Model):
  article = models.ForeignKey(Article, on_delete=models.CASCADE)
  author = models.CharField('Автор комментария', max_length=60)
  comment_text = models.TextField('Текст комметария', max_length=500)
  pub_date = models.DateTimeField('Дата публикации', db_index=True, auto_now_add=True)

  class Meta:
    verbose_name = 'Комментарий'
    verbose_name_plural = 'Комментарии'

  def __str__(self):
    return self.author
  
class Rubric(models.Model):
  name = models.TextField('Название', max_length=30, db_index=True)
  
  def __str__(self):
    return self.name

  class Meta:
    verbose_name_plural = 'Рубрики'
    verbose_name = 'Рубрика'
    ordering = ['name']

Top/views.py
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import FormView
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .models import Article, Comment, Rubric
from django.views.generic.base import View
from django.contrib.auth import logout
# Опять же, спасибо django за готовую форму аутентификации.
from django.contrib.auth.forms import AuthenticationForm
# Функция для установки сессионного ключа.
# По нему django будет определять, выполнил ли вход пользователь.
from django.contrib.auth import login

def index(request):
  Articles = Article.objects.all()
  Rubrics = Rubric.objects.order_by('-id')
  return render(request, 'Top/list.html', {"Articles": Articles, 'Rubrics': Rubrics})

def poisck(request):
  title_poisck = request.POST['poisck']
  try:
    Articles = Article.objects.filter(title = title_poisck)
    Rubrics = Rubric.objects.order_by('-id')
  except:
    raise Http404('Ошибка 404')
  
  return render(request, 'Top/list.html', {"Articles": Articles, 'Rubrics': Rubrics})
    
def by_rubric(request, rubric_id):
  Articles = Article.objects.filter(rubric=rubric_id)
  Rubrics = Rubric.objects.order_by('-id')
  current_rubric = Rubric.objects.get(id=rubric_id)
  context = {'Articles': Articles, 'Rubrics': Rubrics, 'current_rubric': current_rubric}
  return render(request, 'Top/by_rubric.html', context)

def detail(request, article_id):
  try:
    a = Article.objects.get( id = article_id );
  except:
    raise Http404('Ошибка 404')
  
  Comments = a.comment_set.order_by('-pub_date')
  
  return render(request, 'Top/detail.html', {'Article': a, 'Comments': Comments})

def list_comment(request, article_id):
  try:
    a = Article.objects.get( id = article_id );
  except:
    raise Http404('Ошибка 404')
  
  a.comment_set.create(comment_text = request.POST['text_comment'], author = request.user.username )
  
  return HttpResponseRedirect( reverse('blog:detail', args=(a.id,)) )


# Авторизация и Регестрация
class RegisterFormView(FormView):
    form_class = UserCreationForm

    # Ссылка, на которую будет перенаправляться пользователь в случае успешной регистрации.
    # В данном случае указана ссылка на страницу входа для зарегистрированных пользователей.
    success_url = '/accounts/login/'

    # Шаблон, который будет использоваться при отображении представления.
    template_name = "Top/register.html"

    def form_valid(self, form):
        # Создаём пользователя, если данные в форму были введены корректно.
        form.save()

        # Вызываем метод базового класса
        return super(RegisterFormView, self).form_valid(form)

class LoginFormView(FormView):
    form_class = AuthenticationForm

    # Аналогично регистрации, только используем шаблон аутентификации.
    template_name = "login.html"

    # В случае успеха перенаправим на главную.
    success_url = "/"

    def form_valid(self, form):
        # Получаем объект пользователя на основе введённых в форму данных.
        self.user = form.get_user()

        # Выполняем аутентификацию пользователя.
        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)

class LogoutView(View):
    def get(self, request):
        # Выполняем выход для пользователя, запросившего данное представление.
        logout(request)

        # После чего, перенаправляем пользователя на главную страницу.
        return HttpResponseRedirect("/")

Top/templates/Top/by_rubric.html
{% extends "base.html" %}

{% block title %}Главное - {{ current_rubric.name }}{% endblock %}

{% block content %}
<section class='container'>
<div class='row row-article'>
{% for Article in Articles %}
<article class='Article col-10 col-sm-10 col-md-5 col-lg-4 col-xl-4'>
  <div clas='scale div_img'>
    <img src="{{ Article.image.url }}" alt="Картинка"
      class='article_img scale col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12'>
  </div>
  <h2 class='article_title'><a href='{% url "blog:detail" Article.id %}' class='article_title'>{{ Article.title }}</a>
  </h2>
  <p>{{ Article.published_date }}</p>
  <p class='author_create'>Автор идеи: <span>{{ Article.create_author }}</span></p>
  <p><a href="#">Рубрика: {{ Article.rubric.name }}</a></p>
</article>
{% endfor %}
</div>
</section>
{% endblock %}

Top/templates/Top/detail.html
{% extends "base.html" %}

{% block title %}
  {{ Article.title }}
{% endblock %}

{% block content %}
<style>
  .Article_text {
    font-size: 16px;
    font-weight: 600;
  }
  .Article_title {
    font-weight: 600;
  }
  .detail_width_img {
    margin: auto;
  }
</style>


<div class=''>
  {% if Article.image %}
  <div style='max-width: 650px; ' class='detail_width_img'>
    <img src="{{ Article.image.url }}" alt="Картинка" style='padding-left: 0; width: 100%;' class=''>
  </div>
  {% else %}
  <div style='max-width: 650px; ' class='detail_width_img'></div>
  {% endif %}
  <h1 class='Article_title'>{{ Article.title }}</h1>
  <p>{{ Article.published_date }}</p>
  <p class='Article_text'>{{ Article.text }}</p>
  <h2>Комметарии:</h2>
  <div>

    {% if Comments %}
      {% for Comment in Comments %}
        
          <strong>{{ Comment.author }}</strong>
          <p>{{ Comment.comment_text }}</p>
      {% endfor %}
    {% else %}
      Комментов нет =(
    {% endif %}
    

  </div>
  {% if user.is_authenticated %}
  <form action="{% url 'blog:list_comment' Article.id %}" method="POST">
    {% csrf_token %}

    <textarea name='text_comment' placeholder="Ваш комментарий" required cols='30' rows='5'></textarea><br>
    <button type="submit">Отправить</button>
  </form>
  {% else %}
    <h2>
      <a href="{% url 'login'%}?next={{request.path}}">Войдите чтобы оставлять комменты</a>
    </h2>
  {% endif %}

</div>
{% endblock %}

Top/templates/Top/list.html
{% extends "base.html" %}

{% block content %}
<style>
  .No_article_h1 {
    font-weight: 900;
    font-size: 4em;
    color: rgba(0, 255, 234, 0.733);
    text-align: center;
  }
</style>

<section class='container'>
<div class='row row-article'>
  {% if Articles %}
    {% for Article in Articles %}
            <article class='Article col-10 col-sm-10 col-md-5 col-lg-3 col-xl-3 row'>
              <div clas='scale div_img pr-0 col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12'>
                <img src="{{ Article.image.url }}" alt="Картинка" class='article_img scale col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12'>
              </div>
              <h2 class='article_title'><a href='{% url "blog:detail" Article.id %}' class='article_title'>{{ Article.title }}</a></h2>
              <p>{{ Article.published_date|date:"d.m.Y" }}</p>
              <p><a href="#">Рубрика: {{ Article.rubric.name }}</a></p>
            </article>
    {% endfor %}
  {% else %}
    <h1 class='No_article_h1 display-1'>Статьи не найдены =(((</h1>
  {% endif %}
</div>
</section>
{% endblock %}

Top/templates/Top/register.html
{% extends "base.html" %}

{% block content %}
  <form class='form_register' action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Зарегестрироваться</button>
  </form>
{% endblock %}

Top/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'Top/style.css' %}">
  <meta charset="UTF-8">
  <title>{% block title %}Главное{% endblock %}</title>
</head>
<body>
  <header class=''>
  {% block header %}
    <nav class='navbar navbar-expand-md navbar-light bg-light header sticky-top'>
      <div class="container-fluid">
        <h1 class='row TSOF'>
          <a href="{% url 'blog:index' %}" class='TOPinHEADER'>
            TOP SLUT OF <div class='Kamch'>KAMCHATKA</div>
          </a>
        </h1>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target='#headerbutton'>
          <span class='navbar-toggler-icon'></span>
        </button>
        <div class='collapse navbar-collapse rubric_list' id='headerbutton'>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item rubric_header">
              <a href="{% url 'login'%}?next={{request.path}}" class="nav-link">Вход</a>
            </li>
            <li class="nav-item rubric_header">
              <a href="{% url 'blog:register' %}" class="nav-link">Регестрация</a>
            </li>
            <li class="nav-item rubric_header">
              <a href="{% url 'logout'%}?next={{request.path}}" class="nav-link">Выход</a>
            </li>
            <li class="nav-item">
             <form action="{% url 'blog:poisck' %}" method="POST" class='form_poisck float-left float-sm-left float-md-left'>
              {% csrf_token %}
              <input class='poisck_input' type="text" name='poisck' placeholder="Поиск">
              <button type="submit" class='buttom_search'>
                <a href="#" class=''>
                  <img src='{% static "image/search.png" %}' alt="Картинка" class='img_search'>
                </a>
              </button>
             </form>
            </li>
          </ul>
        </div>
      </div>

  {% endblock %}
  </header>

  

  
  <section class='content'>
  <div class='row'>
    <div class='col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12'>
      {% block content %} 
      {% endblock %}
    </div>
  </div>
  </section>

  <style>
    /*    ШРИФТЫ    */

@font-face {
  font-family: Bareona;
  src: url(fonts/Bareona.ttf); 
}

@font-face {
  font-family: Playtoy;
  src: url(fonts/Playtoy.ttf)
}

@font-face {
  font-family: 19104;
  src: url(fonts/19104.ttf)
}

/*    КОНЕЦ ШРИФТОВ    */

* {
  margin: 0;
  padding: 0;
}

body {
  color:  rgb(0, 0, 0);
  font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
  max-width: 100%;
  height: 100%;
  overflow-x: hidden;
}

a {
  color: rgb(7, 7, 7);
  text-decoration: none;
}

div a {
  text-decoration: none;
}

.header {
  min-width: 100%;
  position: fixed;
  z-index: 3;
  max-width: 100%;
  padding: 0;
  margin-bottom: 10px;
  box-shadow: 0 0 10px 1px #888;
}

.navbar-toggler {
  margin-right: 20px;
}

ul .nav-item {
  margin-left: 15px;
}

.rubric_list {
  padding-bottom: 5px;
  margin-right: 40px;
}

.rubric_header {
  color: rgb(0, 102, 255) !important;
  text-decoration: none;
  margin: 5px;
  background-image: linear-gradient(rgb(0, 102, 255), rgb(0, 102, 255));
  background-position: 0% 100%;
  background-repeat: no-repeat;
  background-size: 0% 2px;
  transition: background-size .3s;
}

.rubric_header:hover {
  color: rgb(0, 102, 255);
  background-size: 100% 2px;
}
.nav-link:hover {
  color: rgb(0, 93, 231) !important;
}

.rubric_header:focus {
  color: rgb(0, 102, 255);
  background-size: 100% 2px;
}
.nav-link:focus {
  color: rgb(0, 93, 231) !important;
}

.div_img {
  display: block;
}

.article_img {
  display: block;
  padding-left: 0;
  padding-right: 0;
} 

@media (max-width: 767px) {
  .Article {
    min-height: 0px;
  }
}

@media (min-width: 768px) {
        .article_img {
          height: 200px;
        }
        .Article {
          height: 400px !important;
        }
        .form_poisck {
          margin-top: 10px !important;
        }
    }

    @media (min-width: 992px) {
        .article_img {
            height: 200px;
            width: auto;
        }
        .Article {
          height: 400px;
          margin-left: 30px !important;
        }
        .form_poisck {
          margin-top: 10px !important;
        }
    }

    @media (min-width: 1200px) {
        .article_img {
            height: 200px
        }
        .Article {
          height: 400px;
          padding-right: 0 !important;
        }
        .form_poisck {
          margin-top: 10px !important;
        }
    }

    @media (min-width: 1365px) {
        .article_img {
            height: 200px;
            padding-right: 0 !important;
        }
        .Article {
          height: 400px;
          padding-right: 0 !important;
          margin-left: 30px !important;
        }
        .form_poisck {
          margin-top: 10px !important;
        }
    }

@media (min-width: 1500px) {
  .article_img {
    height: 200px;
    padding-right: 0 !important;
  }

  .Article {
    height: 400px;
    padding-right: 0 !important;
    margin-left: 30px !important;
  }

  .form_poisck {
    margin-top: 10px !important;
  }
}

.article_img {
  width: 100% !important;
  padding-right: 0 !important;
}

.div_img {
  padding-right: 0 !important;
  width: 100% !important;
}
 
.content {
  margin-top: 80px;
}

.author_create {
  padding-bottom: auto;
  color: #000;
  font-size: 13px;
  font-weight: 100;
}

.Article {
  display: block;
  background-color: rgba(255, 255, 255, 0.9);
  padding-left: 0 !important;
  padding-right: 0 !important;
  margin-bottom: 20px;
  box-shadow: 0px 1px 3px 1px #666666;
  height: 400px;
  transition: .4s;
}

.Article * {
  padding-left: 0 !important;
}

.Article:hover {
  position: relative;
  z-index: 2;
  transform: scale(1.03);
}

.article_title {
  font-weight: 500;
}

.article_title:hover {
  text-decoration: none;
  color: #000;
}

 .TSOF .TOPinHEADER {
  font-family: 19104;
  font-weight: 800;
  font-size: .6em;
  padding-top: 5px;
  color: rgb(0, 0, 0);
  text-decoration: none;
}

.TSOF .TOPinHEADER:hover {
  text-decoration: none;
}

.Kamch {
  font-family: 19104;
  font-size: .9em;
  font-weight: 800;
}

.article_text {
  font-size: 13px;
}

.article_content {
  padding-left: 5px;
}

.row { 
  padding-left: 30px;
}

.container {
  padding-right: 0 auto;
  display: inline-block;
}

.form_poisck {
  display: flex;
  background: #fff;
  width: 190px;
  border: 1px solid rgba(0, 247, 255, 0.6);
  border-radius: 10px !important;
}

.form_poisck .poisck_input {
  padding: 1px;
  border-top: 1px solid rgba(0, 247, 255, 0.6);
  border-left: 1px solid rgba(0, 247, 255, 0.6);
  border-bottom: 1px solid rgba(0, 247, 255, 0.6);
  border-top-left-radius: 10px;
  border-bottom-left-radius: 10px;
}

.form_poisck:hover {
  border-color: rgba(0, 162, 255, 0.89);
  transition: .5s;
}

.form_poisck * {
  outline: none;
  border: none;
}

.buttom_search {
  padding-bottom: 26px !important;
  width: 30px;
  height: 27px;
  background: none;
  border-top: 1px solid rgba(0, 247, 255, 0.6);
  border-right: 1px solid rgba(0, 247, 255, 0.6);
  border-bottom: 1px solid rgba(0, 247, 255, 0.6);
  border-top-right-radius: 10px;
  border-bottom-right-radius: 10px;
}

.img_search {
  width: 20px;
}
  </style>
</body>
</html>